---
- name: Preconfig
  hosts: all
  roles:
    - tags: preconfig
      role: preconfig

- name: Leader
  hosts: leader
  roles:
    - role: swarm_init
      tags: swarm_init
    - role: set_labels
      tags: set_labels
    - role: registry_init
      tags: registry_init

- name: Managers
  hosts: managers
  roles:
    - role: swarm_join
      type: manager
      tags: swarm_join
    - role: set_labels
      tags: set_labels

- name: Workers
  hosts: workers
  roles:
    - role: swarm_join
      type: worker
      tags: swarm_join
    - role: set_labels
      tags: set_labels
