---
- name: "{{ service.name }} : Создание секрета"
  community.docker.docker_secret:
    state: present
    name: "{{ name }}"
    data_is_b64: true
    labels:
      secret: "{{ data | hash('sha1') }}"
    data: "{{ data | b64encode }}"
