---
- block:
    - include_tasks: ./create-secret.yml
  rescue:
    - name: "{{ service.name }} : Удаление сервиса"
      community.docker.docker_swarm_service:
        name: "{{ service.name }}"
        state: absent

    - include_tasks: ./create-secret.yml
